image: maven:3.6.3

pipelines:
  default:
    - parallel:
      - step:
          name: Build
          caches:
            - maven
          script:
            - mvn compile --file pom.xml
      - step:
          name: Test
          caches:
            - maven
          script:
            - mvn test --file pom.xml
      - step:
          name: Mutation Coverage Test
          caches:
            - maven
          script:
            - mvn test
            - mvn org.pitest:pitest-maven:mutationCoverage
